import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy — Klipprr",
  description: "Privacy Policy for Klipprr.",
  alternates: { canonical: "/privacy" },
};

export default function PrivacyPage() {
  const webPageJsonLd = {
    "@context": "https://schema.org",
    "@type": "WebPage",
    name: "Privacy Policy — Klipprr",
    url: "https://klipprr.com/privacy",
    dateModified: "2026-04-10",
  };
  const breadcrumbJsonLd = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "Home", item: "https://klipprr.com/" },
      { "@type": "ListItem", position: 2, name: "Privacy", item: "https://klipprr.com/privacy" },
    ],
  };
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(webPageJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }}
      />
      <h1>Privacy Policy</h1>
      <p>
        <strong>Effective date:</strong> March 17, 2026
      </p>
      <p>
        This Privacy Policy explains how <strong>Klipprr</strong> (“we”, “us”) collects, uses, and shares
        information when you use our website and desktop application (together, the “Service”).
      </p>

      <h2>Who we are</h2>
      <p>
        Klipprr is operated by a company registered in <strong>Slovakia (EU)</strong>. If you need our full
        legal entity details for an invoice, contract, or data request, contact us at{" "}
        <a href="mailto:hello@klipprr.com">hello@klipprr.com</a>.
      </p>

      <h2>Information we collect</h2>
      <h3>Information you provide</h3>
      <ul>
        <li>
          <strong>Account information</strong> (such as email address, password-based login credentials, and
          authentication identifiers).
        </li>
        <li>
          <strong>Billing-related information</strong> (such as subscription status and Stripe customer/subscription
          identifiers). Payment card details are processed by Stripe; we do not store full card numbers.
        </li>
        <li>
          <strong>Support communications</strong> (messages you send to us, and any files/logs you choose to share).
        </li>
      </ul>

      <h3>Information collected automatically</h3>
      <ul>
        <li>
          <strong>Log and device information</strong> (such as IP address, user-agent, timestamps, and pages/actions)
          generated by our hosting and security systems.
        </li>
        <li>
          <strong>Cookies/local storage</strong> that are required for sign-in flows and basic website functionality.
          See our <a href="/cookies">Cookie Policy</a>.
        </li>
      </ul>

      <h3>Content and usage data</h3>
      <p>
        The Service lets you create clips from third-party sources (for example: YouTube, Twitch, X, Instagram, Vimeo)
        and from local video files. Depending on how you use the Service, we may process:
      </p>
      <ul>
        <li>
          <strong>Input URLs</strong> you provide and related metadata needed to perform the requested action.
        </li>
        <li>
          <strong>Plan/entitlement usage</strong> (such as clip counts and feature access) to enforce limits and prevent abuse.
        </li>
      </ul>
      <p>
        We do not intend to permanently store your full video files on our servers. Any diagnostic logs are typically stored
        locally on your device unless you choose to share them with us.
      </p>

      <h2>How we use information</h2>
      <ul>
        <li>
          <strong>Provide the Service</strong> (account creation, authentication, feature access, and license/subscription enforcement).
        </li>
        <li>
          <strong>Process payments</strong> and manage subscriptions.
        </li>
        <li>
          <strong>Security and fraud prevention</strong>, including preventing abuse and protecting the Service.
        </li>
        <li>
          <strong>Support</strong>, troubleshooting, and improving reliability.
        </li>
        <li>
          <strong>Legal compliance</strong>, such as accounting and tax recordkeeping.
        </li>
      </ul>

      <h2>Legal bases (EEA/UK)</h2>
      <p>
        If you are in the EEA/UK, we process personal data under one or more of the following legal bases:
        contract necessity (to provide the Service), legitimate interests (security and service improvement),
        consent (where required, e.g. certain cookies/marketing), and legal obligation (e.g. tax and accounting).
      </p>

      <h2>How we share information</h2>
      <p>We share information with service providers (“processors”) that help us run the Service, including:</p>
      <ul>
        <li>
          <strong>Supabase</strong> (authentication, database, and related infrastructure).
        </li>
        <li>
          <strong>Stripe</strong> (payments and subscription management).
        </li>
        <li>
          <strong>Vercel</strong> (website hosting and related logs).
        </li>
        <li>
          <strong>Cloudflare</strong> (domain/DNS and potentially security/network services, depending on configuration).
        </li>
      </ul>
      <p>
        We may also share information if required by law, to enforce our terms, or to protect the rights, safety, and security of
        Klipprr, our users, or others.
      </p>

      <h2>International data transfers</h2>
      <p>
        Some of our providers may process data outside the EEA. Where applicable, we rely on appropriate safeguards
        (such as standard contractual clauses) to protect personal data.
      </p>

      <h2>Data retention</h2>
      <p>
        We keep personal data only as long as necessary for the purposes described above. For example, account data is retained
        while your account is active; billing and transaction records may be retained longer to meet legal obligations; and logs
        are typically retained for shorter periods for security and troubleshooting.
      </p>

      <h2>Your rights</h2>
      <p>
        Depending on your location, you may have rights to access, correct, delete, or export your personal data, and to object to
        or restrict certain processing. To submit a request, contact{" "}
        <a href="mailto:hello@klipprr.com">hello@klipprr.com</a>.
      </p>

      <h2>Children</h2>
      <p>
        The Service is not directed to children, and you must be at least 13 years old (or older if required by your local law) to
        use the Service.
      </p>

      <h2>Changes</h2>
      <p>
        We may update this Privacy Policy from time to time. We will post the updated version on this page and update the effective
        date.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about privacy? Email{" "}
        <a href="mailto:hello@klipprr.com">hello@klipprr.com</a>.
      </p>
    </>
  );
}
